name: Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::779846795588:role/automation-todo
          role-session-name: github-actions
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          IMAGE_URI=779846795588.dkr.ecr.ap-southeast-1.amazonaws.com/todo-front
          docker build -t $IMAGE_URI:latest .

      - name: Push image to Amazon ECR
        run: |
          IMAGE_URI=779846795588.dkr.ecr.ap-southeast-1.amazonaws.com/todo-front
          docker push $IMAGE_URI:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster todo \
            --service todo-front-service-nz27h57g \
            --force-new-deployment
